marks = []
s1 = int(input("Enter marks of student 1 "))
s2 = int(input("Enter marks of student 2 "))
s3 = int(input("Enter marks of student 3 "))
s4 = int(input("Enter marks of student 4 "))
s5 = int(input("Enter marks of student 5 "))
s6 = int(input("Enter marks of student 6 "))
marks.append(s1)
marks.append(s2)
marks.append(s3)
marks.append(s4)
marks.append(s5)
marks.append(s6)

marks.sort()
print(marks)
